### ISSUE TITLE
DR/Effective Health Tool is using the TBC formula

### ISSUE THREAD

**Issue by Beardruid12** [Tegas/legacy-sim#2]
Hey, just wanted to say your tools are very useful. But I did want to point out the the DR/effective health calculator is using the formula from TBC. The Vanilla Formula is DR = (Armor / (Armor + 400 + 85 * Enemy_Level)). For example, the cap for a level 60 player against a level 63 boss should be 17,265 armor.

**Comment by Tegas** [comment]
Fixed. Thanks!
