### ISSUE TITLE
chance to calculate miss question

### ISSUE THREAD

**Issue by tylerhray** [Tegas/legacy-sim#4]
it seems the way dual wield miss chance is calculated here only applies the dual wield penalty to the baseline miss chance of 5%:

Baseline = 0.05
if (defense_rating - attack_rating >= 11)
   Miss = (defense_rating - attack_rating)*0.002
else if (defense_rating - attack_rating <= 10)
   Miss = (defense_rating - attack_rating)*0.001

function Dual_wield_penalty(x)
   return 0.8*x+0.2

Dual_wield_miss = Dual_wield_penalty(Baseline) + Miss

Should the dual wield formula apply to just the baseline 5% miss chance as in this simulation? The attack table source seems to imply it applies to the overall miss chance "Beaza also tells us that the dual-wield miss chance is 80% of the miss chance calculated above plus 20%, which makes the dual-wield miss formula", making this instead: 

Dual_wield_miss = Dual_wield_penalty(Baseline+Miss)

https://github.com/magey/classic-warrior/wiki/Attack-table#glancing-blows
(original source https://wowwiki.fandom.com/wiki/Miss?oldid=347982)

**Comment by Tegas** [comment]
Yeah, I'm definitely missing that. Looks like it's newer science. I'll update. Thanks for the bug report! <3 

Published the change. Take a look and let me know if it needs more changes.

**Comment by tylerhray** [comment]
looks good! I wasn't sure which was correct since the difference is really minor, and to be honest the original blizz posts are very vague.
BTW this attack table is great, I've used it to accurately match ingame dps within under 5% error and the table distributions match Recount meters very closely.

![attack_table_comparison](https://user-images.githubusercontent.com/13359581/73015772-a3ebc280-3dea-11ea-92c6-7e44b08f9255.PNG)

**Comment by Tegas** [comment]
Excellent. Glad to hear it's useful. :) I've never played melee so this was my attempt to figure out how the mechanics worked.
